[package]
name = "solomon"
version = "0.2.0"
authors = ["PoiScript <poiscript@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
chrono = "0.4.10"
imagesize = "0.8.7"
json = "0.12.0"
lazy_static = "1.4.0"
maud = "0.21.0"
orgize = { version = "0.7.0", default-features = false }
syntect = "3.3.0"
